### PR TITLE
Feature/snapshot check strategy

### PR DESCRIPTION
**Pull request by seunghanhong**
Hi there,

Firstly, thanks for the great job creating an adapter for Azure Synapse. I would like to add a feature to handle check-strategy snapshots.

### CODE REVIEW

**Comment by ebarajas** [comment]
Thanks for the contribution! 

@mattberns Do you mind giving this a quick review?

**Comment by seunghanhong** [comment]
Thanks for looking into it. FYI, I've created a [PR](https://github.com/fishtown-analytics/dbt-integration-tests/pull/6) for dbt-integration-tests to include snapshot testing. It's not fully compatible with Synapse due to tests in dbt_utils. However, I was able to run snapshots (both timestamp and check) with a few tweaks in Synapse.

**Review by mattberns — APPROVED** [review]
@ebarajas I don't have any changes to this. @seunghanhong closed one of the needed gaps here around snapshots.

@seunghanhong Great job! Total sidebar - I see you also might have a strategy for external tables form some of your other repos. Any interest in including external table support here?

**Comment by seunghanhong** [comment]
> @seunghanhong Great job! Total sidebar - I see you also might have a strategy for external tables form some of your other repos. Any interest in including external table support here?

@mattberns @ebarajas Thanks for the review and approval 👍 

Regarding external tables, I see two possible ways: Polybase and COPY statement using dbt run-operation command. I find it a bit messy to implement Polybase because it requires external data source and external file format. We can either assume it's created outside external tables, but that doesn't give full benefits of using dbt-external-tables. I sort of made a basic change to implement Polybase with the assumption. I am open to listen any suggestions how to structure Polybase yaml.

At the moment, I am working on COPY as it is what Microsoft recommends. I am going to implement based on this sample yaml and extend further.
```
version: 2

sources:
  - name: my_source
    database: my_database
    schema: my_dev
  
    tables:
      - name: my_table
        load_type: copy

        external:
          location: 'https://{{ my_storage_account }}.blob.core.windows.net/{{ my_container }}/file_name_*.csv'
          file_type: 'CSV'
          identity: 'Storage Account Key'
          secret: '{{ secret_key }}'
          fieldquote: '"'
          fieldterminator: ','
          rowterminator: '\n'
          firstrow: 2
          dateformat: ymd
          encoding: 'UTF8'
          
        columns:
          - name: col1
            data_type: varchar(255)
            description: "column 1"
          - name: col2
            data_type: varchar(255)
            description: "column 2"
          - name: col3
            data_type: datetime
            description: "column 3"
```
This yaml will execute the following t-sql for the first time run.

```
    CREATE TABLE my_dev.my_table (
        col1 varchar(255),
        col2 varchar(255),
        col3 datetime
    )

    COPY INTO my_dev.my_table
    FROM 'https://my_storage_account.blob.core.windows.net/my_container/file_name_*.csv'
    WITH 
    (
        FILE_TYPE = 'CSV',
        CREDENTIAL = (IDENTITY= 'Storage Account Key', SECRET='super_secret'),
        FIELDQUOTE = '"',
        FIELDTERMINATOR = ',',
        ROWTERMINATOR = '\n',
        FIRSTROW = 2,
        DATEFORMAT = 'ymd',
        ENCODING = 'UTF8'
        ENCODING = 'UTF8'
    );
```

On a side note, would you change dbt-azuresynapse version to align with dbt releases? It helps people easily choose adapter versions.
```
dbt-bigquery==0.18.0
dbt-core==0.18.0
dbt-postgres==0.18.0
dbt-redshift==0.18.0
dbt-snowflake==0.18.0
dbt-sqlserver==0.18.0
```

**Comment by ebarajas** [comment]
@seunghanhong Thanks again!

I think we can definitely match the dbt releases. The one big question I have is how would we show that a version bump is an internal bug fix and not a change in dbt version? I'm thinking of something like `dbt-azuresynapse==0.18.0-1.2.0`, but definitely open to other suggestions. 

Went ahead and opened an issue for further discussion on this: https://github.com/embold-health/dbt-azuresynapse/issues/9

**Pull request merged**
